# 定义了工作流程的名称
name: Build and Deploy
# 当代码推送到'master'分支时触发
on:
  push:
    branches:
      - master
jobs:
  # 构建并发布
  build-and-deploy:
    # 提供写的权限
    permissions:
      contents: write
    # 配置每步步骤
    steps:
      # 检出代码到工作目录
      - name: Checkout
      - uses: actions/checkout@2.3.1

      # 锁定node版本
      - name: lock npm version
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.0

      # 安装与构建
      - name: Install and Build
        run: npm i -g pnpm
          pnpm Install
          pnpm run build
        env:
        NODE_OPTIONS: '--max_old_space_size=4096'
